### PR TITLE
Add build scripts, drop unused userguide files

### PR DESCRIPTION
**Pull request by chalin**
Basic prep for #726

### CODE REVIEW

**Comment by LisaFC** [comment]
OK, this seems to have broken the production build (preview builds are fine) - can you take a look? Looks like

https://app.netlify.com/sites/docsydocs/deploys/6181635e9c73ac0007af55eb

I'll have a poke around at it as well....

**Comment by LisaFC** [comment]
Preview build for contrast: https://app.netlify.com/sites/docsydocs/deploys/61810d8c6e18950008232cd8

**Comment by chalin** [comment]
Yes looking now.

**Comment by chalin** [comment]
Found the issue. Preparing a fix.

**Pull request merged**
