### PR TITLE
Upgrade to Bootstrap 5.3.3

### PR DESCRIPTION
**Pull request by deining**
This PR follows up on #1510 and #1528.
It updates bootstrap dependency to latest released version 5.3.3.

### CODE REVIEW

**Comment by deining** [comment]
Bootstrap is at version `5.3.1` meanwhile. This is now reflected in this PR.

**Comment by deining** [comment]
Bootstrap is at version `5.3.2` meanwhile. This is now reflected in this PR.

**Review by chalin — CHANGES_REQUESTED** [review]
I've added the following clarifying remark at the start of the opening comment of #1528:

> BS 5.3 changes are significant enough that, IMHO, we'll want to careful walkthrough of the [5.3 migration](https://getbootstrap.com/docs/5.3/migration/) details before upgrading Docsy to BS 5.3

All this to say that this PR could be the first to be merged, but only once we're ready to start the migration to 5.3. Which probably won't happen until 24Q1 since I'd like to give non-Bootstrap related issues some love before the year is out.

Of course, feel free to update the PR in the meantime, or you can wait until later.

/cc @LisaFC @geriom @emckean

**Comment by chalin** [comment]
@deining - I'll have time this month to devote to the BS 5.3 upgrade. Do you want to resolve and update this PR or submit a new one?

**Comment by deining** [comment]
> @deining - I'll have time this month to devote to the BS 5.3 upgrade.

Great to hear that!

> Do you want to resolve and update this PR

Done:
* resolved merge conflicts
* updated to latest Bootstrap version 5.3.3

Good luck with your further work!

**Review by chalin — APPROVED** [review]

**Comment by chalin** [comment]
Thanks for the quick update.

**Pull request merged**
