### PR TITLE
 Add params to offlineSearch examples 

### PR DESCRIPTION
**Pull request by svrnm**
While trying out the offline search feature I struggled to get it working until I figured out that the `offlineSearch` should be within `params`.

### CODE REVIEW

**Review by deining — COMMENTED** [review]
Thanks for your contribution! Your suggestion is valid IMHO, I consider it an improvement to the user guide.
Looking at your changes in `search.md`, I realized , that `offlineSearch: true` appears two more times in the subchapters [`Changing the summary length of the local search results`](https://www.docsy.dev/docs/adding-content/search/#changing-the-summary-length-of-the-local-search-results) and [`Changing the maximum result count of the local search`](https://www.docsy.dev/docs/adding-content/search/#changing-the-maximum-result-count-of-the-local-search). Shouldn't we mention `params` at these occurrences  as well? @svrnm: do you want to go for this as well?

**Comment by deining** [comment]
**Additional note**: I just realized that in the [chapter](https://www.docsy.dev/docs/adding-content/search/#adding-the-search-page) documenting how to enable GCSE search engine, the line `gcs_engine_id = "xxxx"` should be within `params` as well. We should address this in a separate ticket/PR IMHO.

**Comment by Marzal** [comment]
> **Additional note**: I just realized that in the [chapter](https://www.docsy.dev/docs/adding-content/search/#adding-the-search-page) documenting how to enable GCSE search engine, the line `gcs_engine_id = "xxxx"` should be within `params` as well. We should address this in a separate ticket/PR IMHO.

Maybe there should be a full review, because there are more references without the params indications :
 - https://www.docsy.dev/docs/adding-content/lookandfeel/#code-highlighting-with-prism
 - https://www.docsy.dev/docs/adding-content/repository-links/

**Comment by svrnm** [comment]
@deining done, I fixed the other 2 places as well

**Comment by chalin** [comment]
@deining - is this PR good to go?
@Marzal or @deining - consider creating an issue for the other sections, thanks.

**Comment by chalin** [comment]
@deining - is this ready?

**Review by deining — APPROVED** [review]
LGTM

**Review by chalin — APPROVED** [review]

**Comment by svrnm** [comment]
thanks for merging :-)

**Pull request merged**
