### PR TITLE
iframe shortcode #530

### PR DESCRIPTION
**Pull request by narrenfrei**
This is my 1st version for an iframe shortcode discussed in #530 

The complicated thing about writing a general shortcode for iframes is, how to calculate the needed height of the iframe. So i defined some parameter to control the height:

1. As default the shortcode tries to calculate the needed height for the embedded content by JS (https://stackoverflow.com/a/14618068). But this is only possible, if the embedded content is on the same domain (https://stackoverflow.com/questions/22086722/resize-cross-domain-iframe-height and )
2. If this is not possible a height of 98vh will be used as default.

### CODE REVIEW

**Comment by narrenfrei** [comment]
iframe shortcode and manual should be ready for merging

**Comment by narrenfrei** [comment]
Manual can be find at https://deploy-preview-544--docsydocs.netlify.app/docs/adding-content/shortcodes/#iframe

**Comment by LisaFC** [comment]
Sorry I haven't had a chance to review this yet - I'll take a look today! Looks excellent from a quick read.

**Comment by narrenfrei** [comment]
@LisaFC My PR included also content for developing the iframe shortcode in the userguide, which you also merged into the master. I think, the wasn't your intention, was it?

https://github.com/google/docsy/tree/master/userguide/content/en/docs/dev-test-content

**Comment by deining** [comment]
> @LisaFC My PR included also content for developing the iframe shortcode in the userguide, which you also merged into the master. I think, the wasn't your intention, was it?

Just realized this, too.
Should be removed IMHO.

**Comment by LisaFC** [comment]
Gah, sorry, my mistake. Let me remove that....

**Comment by LisaFC** [comment]
Errant directory removed!

**Pull request merged**
