### PR TITLE
README.md: add badges at top of page

### PR DESCRIPTION
**Pull request by deining**
This PR adds status badges for repo and netlify status, releases, license, contributors and twitter at the top of `README.md`.

### CODE REVIEW

**Review by chalin — APPROVED** [review]
I'd move the badges to be under the page title. I'm not sure about Twitter (will discuss with PSC). Otherwise, LGTM

**Comment by chalin** [comment]
PSC suggests we drop the Twitter handle.

**Comment by deining** [comment]
Dropped the twitter handle and moved the badges under the title header, as requested.

**Review by chalin — APPROVED** [review]
✨

**Pull request merged**
