### PR TITLE
taxonomy support #272 #324 #539

### PR DESCRIPTION
**Pull request by narrenfrei**
As mentioned in #272 and #324 I continued the development of support for taxonomies / tagging.
Because I've decided to code the taxonomy functionality from scratch, I've closed #539 and made a new PR.

You can catch a current preview at https://deploy-preview-554--docsydocs.netlify.app/docs/dev-test-content/
At the moment it's completely WIP and the special pages for taxonomies are very raw.
Some commits for this PR will follow the next days.

### CODE REVIEW

**Comment by narrenfrei** [comment]
A (very) first version of the taxonomy support is ready to get feedback ;-)

I think all needed basic functionality should work. But I'm still working on the layout.

**Comment by narrenfrei** [comment]
Also blog posts now support taxonomies: https://deploy-preview-554--docsydocs.netlify.app/blog/
The taxonomy page with all articles of a specific term shows with an icon, if the tagged article comes from the docs or blog section: https://deploy-preview-554--docsydocs.netlify.app/tags/tag-1/

I have to tidy up the code a little bit and write a manual, then the PR should be ready for merging.

Are there any comments or further wishes?

**Comment by narrenfrei** [comment]
I've now tested also the multi language support for taxonomies:

- The taxonomy terms associated content gets only counted and linked WITHIN the language!
- The control parameters for the taxonomy support should work also language specific (see: https://github.com/narrenfrei/docsy/blob/abf1e3410019aa8a4613aacdf4e9b08a43d7564f/userguide/config.toml#L90)
  - Also the new ones, I've designed for display the taxonomies from an page or clouds in the right sidebar.

I think this should be fine as standard behavior for most situations, shouldn't it?

**Comment by marcelbaumann** [comment]
Please release it. We will start to include the features on public sites and provide learnings.

**Comment by narrenfrei** [comment]
> Please release it. We will start to include the features on public sites and provide learnings.

From my side the PR could get merged quite soon. The functionality is ready. But the manual is not ready and some code cleaning isn't done. 

@LisaFC Is it OK for you, when we release the taxonomy support in two steps or would you like to wait for the whole thing?

**Comment by LisaFC** [comment]
I'm ok with releasing in two steps if there are community members looking to use the feature - is it usable now even though it doesn't have complete docs?

**Comment by narrenfrei** [comment]
> I'm ok with releasing in two steps if there are community members looking to use the feature - is it usable now even though it doesn't have complete docs?

I'll try to write at least a short manual tomorrow, then you can release this PR.

**Comment by narrenfrei** [comment]
The planned functionality of taxonomy support is now (hopefully) ready. You can see a page which shows what's possible at https://deploy-preview-554--docsydocs.netlify.app/docs/dev-test-content/

I've defined 2 quite common layouts for tags and also 1 showcase what's also possible with the taxonomies:

1. The taxonomy "fruits" is only a showcase, what you can do with taxonomies.
2. The taxonomy "text tags" shows a simple text tags layout.
3. All other taxonomies have tag typical layout.

==> What should be the standard layout for the taxonomies - example 2 or 3?
==> Should I make a switch in the settings to toggle between 2 and 3?

I had also to restructure the right sidebar a bit: Before my PR the the repository links where in the div.td-toc and the div.td-toc was the right sidebar itself. As we now get more content in the right sidebar, I restructured it a little bit:

- aside.td-sidebar-toc
  - div.td-page-meta
  - div.td-toc
  - div.taxonomy-terms-cloud for each taxonomy shown in the sidebar

As I introduced a `aside` element for the right sidebar, I also changed the `div` from the left sidebar to a `aside` element. If adapted the CSS to get the old layout. But this may cause some problems, when a project have a customized stylesheet. But I think the markup is now a little bit more stringent.

@LisaFC Is this OK for you?

The next step will be a first version of the manual.

**Comment by narrenfrei** [comment]
First version of manual is online: https://deploy-preview-554--docsydocs.netlify.app/docs/adding-content/taxonomy/

**Comment by narrenfrei** [comment]
From my side it should be ready for merging, except some open questions and comments (see above). At the moment there are some conflicts with master which I should take a look.

And there is a lot of dev content in the userguide.
@LisaFC Is there a possibility to show the taxonomy functionality within the userguide? This is also a general question for other new features. It think, it would be great when there would be a "showroom" within the userguide, wouldn't it?

**Comment by narrenfrei** [comment]
@LisaFC @emckean Same problem as in #518
After rebase on the current Docsy master the google-cla bot can't verify author consent.

From my side this PR would be ready, except deleting my dev content. And a comment to my questions above would be nice ;-)

__Question block 1:__
> I've defined 2 quite common layouts for tags and also 1 showcase what's also possible with the taxonomies:
> The taxonomy "fruits" is only a showcase, what you can do with taxonomies.
> The taxonomy "text tags" shows a simple text tags layout.
> All other taxonomies have tag typical layout.
> ==> What should be the standard layout for the taxonomies - example 2 or 3?
> ==> Should I make a switch in the settings to toggle between 2 and 3?
Here you can see the different layouts: https://deploy-preview-554--docsydocs.netlify.app/docs/dev-test-content/

__Question block 2:__
> I had also to restructure the right sidebar a bit: Before my PR the the repository links where in the div.td-toc and the div.td-toc was the right sidebar itself. As we now get more content in the right sidebar, I restructured it a little bit:
> 
> - aside.td-sidebar-toc
>   - div.td-page-meta
>   - div.td-toc
>   - div.taxonomy-terms-cloud for each taxonomy shown in the sidebar
>
> As I introduced a aside element for the right sidebar, I also changed the div from the left sidebar to a aside element. If adapted the CSS to get the old layout. But this may cause some problems, when a project have a customized stylesheet. But I think the markup is now a little bit more stringent.
> 
> @LisaFC Is this OK for you?

__Question block 3:__
> Is there a possibility to show the taxonomy functionality within the userguide? This is also a general question for other new features. It think, it would be great when there would be a "showroom" within the userguide, wouldn't it?
For the taxonomy support this would mean, that we would have to enable taxonomies in the userguide. I don't know if you'd like this ;-)

**Comment by narrenfrei** [comment]
As the PR is ready from my side, I've removed the WIP in the label.

When merging you should exclude:

- config.toml
- userguide/content/blog
- userguide/content/en/docs/dev-test-content
- userguide/content/no

**Comment by LisaFC** [comment]
I'm really puzzled by the cla-bot thing - all the commits are by you? Let me dig into a bit - @emckean can hopefully shed some light on it too (though it is a public holiday where she is today so she may not be online).

**Comment by narrenfrei** [comment]
> I'm really puzzled by the cla-bot thing - all the commits are by you? Let me dig into a bit - @emckean can hopefully shed some light on it too (though it is a public holiday where she is today so she may not be online).

Everythig I've changed, is in commits by me. But when I take a view on the history of all commits listed in this PR, following commits got a red X from cla-bot:

- https://github.com/google/docsy/pull/554/commits/acad4cd22ee5897049df7849d52798c951ada16d from @deining
- https://github.com/google/docsy/pull/554/commits/cf71c6226339dd2cc25ae16ec8fcbd4ea071374d from @dholbach

**Comment by dholbach** [comment]
Re: #574 - that's bizarre. I signed the commit and it's not my first to be accepted into `docsy`... :man_shrugging:

**Comment by narrenfrei** [comment]
I'm everything else than a git specialist. - Is it possible, that I've made something wrong at `git rebase`?

```
git remote add upstream https://github.com/google/docsy.git
git fetch upstream
git pull upstream master
git checkout dev-taxonomy-2
git rebase master
```

**Comment by deining** [comment]
>     * acad4cd from @deining

Indeed, acad4cd is different from my previous commits in the sense, that I used my company email address, while with all other commits were done woth my Gmail account (this was not done on purpose, I just worked on a different computer). My company email address is listed (besides my gmail address) in the Email Settings of my GitHub account, I guess that's why I was able to successfully commit acad4cd.
I have no idea how to overcome that.

**Comment by narrenfrei** [comment]
Would be great, if we could get this merged soon.

**Comment by narrenfrei** [comment]
@LisaFC @emckean
When the google-cla bot issue is solved, please take a look at my questions above (https://github.com/google/docsy/pull/554#issuecomment-850177326) before you merge the PR. I would like the set the preferred standard behavior and delete the not needed style definitions (especially for the "fruits showcase").

**Comment by narrenfrei** [comment]
> > ```
> > * acad4cd from @deining
> > ```
> 
> 
> Indeed, [acad4cd](https://github.com/google/docsy/commit/acad4cd22ee5897049df7849d52798c951ada16d) is different from my previous commits in the sense, that I used my company email address, while with all other commits i used my Gmail account (this was not done on purpose, I just worked on a different computer). My company email address is listed (besides my gmail address) in the Email Settings of my GitHub account, I guess that's why I was able to successfully commit [acad4cd](https://github.com/google/docsy/commit/acad4cd22ee5897049df7849d52798c951ada16d).
> 
> I have no idea how to overcome that.

@deining I really don't know how the google-cla bot works, but beside the listed email addresses in Github there also exist the with you Google account associated addresses.

Maybe you could check you associated addresses here and add it if needed? https://cla.developers.google.com/clas
Or sign a additional CLA with your work email address?

**Comment by deining** [comment]
> @deining I really don't know how the google-cla bot works

Me neither :-(

> Maybe you could check you associated addresses here and add it if needed?

Indeed, my email address at work was missing here. I Just added it. Can you please recheck if that cures the problem?

**Comment by narrenfrei** [comment]
@googlebot I consent

**Comment by narrenfrei** [comment]
> > @deining I really don't know how the google-cla bot works
> 
> Me neither :-(
> 
> > Maybe you could check you associated addresses here and add it if needed?
> 
> Indeed, my email address at work was missing here. I Just added it. Can you please recheck if that cures the problem?

Could you try once more to leave a `@googlebot I consent` in this PR? And if this doesn't help, it's really on @LisaFC and @emckean to jump in.

**Comment by deining** [comment]
@googlebot I consent.

**Comment by narrenfrei** [comment]
@deining Thank you for this last try, but I'm done. (Or in good old German: Ich bin mit meinem Latein am Ende.)

@LisaFC Please help us!

**Comment by RichieEscarez** [comment]
In my experience, the only way to get past this is to use the correct email address. There are a couple of complicated ways to do this (like removing that commit and replacing the changes) but I think the easiest I've found is to replace the author of that specific commit: https://gist.github.com/trey/9588090

**Comment by narrenfrei** [comment]
> ... the easiest I've found is to replace the author of that specific commit: https://gist.github.com/trey/9588090

@RichieEscarez Who has to this? I as PR author? @deining as the original Author of the commit? A Docsy admin?

What I can't understand: the commit with the wrong email address is already part of the official Docsy master branch (as I made a rebase on the current master to get my dev branch up to date), isn't it? When we only change the author in this PR, it will the same problem with all coming PRs touching the same file, won't it? I have already the same problem with another PR.

**Comment by RichieEscarez** [comment]
I see. Sorry about that. I missed that your PR got blocked after rebasing with HEAD. To answer your question, a member on the Docsy team will need to do the rebase/author fixing. @LisaFC or @emckean any input here?

**Comment by RichieEscarez** [comment]
This should be good to go now.

The issue was actually that we needed to tell the @googlebot that the rebase and inclusion of all other commit is okay (error was not a missing CLA but `need_author_consent`). 

Ive added new labels `cla: yes/no` that the Docsy repo admins can use to manually verify and override this type of validation check.

**Comment by LisaFC** [comment]
FINALLY! Thanks everyone for your patience and thanks so much to @RichieEscarez for figuring out what we needed to do.

**Comment by narrenfrei** [comment]
Thanks everyone for the help to get this PR merged.

**Comment by narrenfrei** [comment]
> As the PR is ready from my side, I've removed the WIP in the label.
> 
> 
> 
> When merging you should exclude:
> 
> 
> 
> - config.toml
> 
> - userguide/content/blog
> 
> - userguide/content/en/docs/dev-test-content
> 
> - userguide/content/no

@LisaFC You habe merged also my test content into the master. Sorry that I have left it in the PR. I think it's easier for you, if I delete it myself before push it into the PR, isn't it?

**Comment by narrenfrei** [comment]
> @LisaFC @emckean Same problem as in #518
> 
> After rebase on the current Docsy master the google-cla bot can't verify author consent.
> 
> 
> 
> From my side this PR would be ready, except deleting my dev content. And a comment to my questions above would be nice ;-)
> 
> 
> 
> __Question block 1:__
> 
> > I've defined 2 quite common layouts for tags and also 1 showcase what's also possible with the taxonomies:
> 
> > The taxonomy "fruits" is only a showcase, what you can do with taxonomies.
> 
> > The taxonomy "text tags" shows a simple text tags layout.
> 
> > All other taxonomies have tag typical layout.
> 
> > ==> What should be the standard layout for the taxonomies - example 2 or 3?
> 
> > ==> Should I make a switch in the settings to toggle between 2 and 3?
> 
> Here you can see the different layouts: https://deploy-preview-554--docsydocs.netlify.app/docs/dev-test-content/
> 
> 
> 
> __Question block 2:__
> 
> > I had also to restructure the right sidebar a bit: Before my PR the the repository links where in the div.td-toc and the div.td-toc was the right sidebar itself. As we now get more content in the right sidebar, I restructured it a little bit:
> 
> > 
> 
> > - aside.td-sidebar-toc
> 
> >   - div.td-page-meta
> 
> >   - div.td-toc
> 
> >   - div.taxonomy-terms-cloud for each taxonomy shown in the sidebar
> 
> >
> 
> > As I introduced a aside element for the right sidebar, I also changed the div from the left sidebar to a aside element. If adapted the CSS to get the old layout. But this may cause some problems, when a project have a customized stylesheet. But I think the markup is now a little bit more stringent.
> 
> > 
> 
> > @LisaFC Is this OK for you?
> 
> 
> 
> __Question block 3:__
> 
> > Is there a possibility to show the taxonomy functionality within the userguide? This is also a general question for other new features. It think, it would be great when there would be a "showroom" within the userguide, wouldn't it?
> 
> For the taxonomy support this would mean, that we would have to enable taxonomies in the userguide. I don't know if you'd like this ;-)

@LisaFC Should I change anything in my original PR?

**Comment by LisaFC** [comment]
Ah, sorry I didn't notice the test data - I'll remove that now (unless you want to create a PR yourself to remove it?)

**Comment by LisaFC** [comment]
OK, test data now gone!

There are still some tags displayed and some taxonomy settings in config.toml

What is the "Cloud of categories" for?

It's nice to have *some* tag info in the userguide so users can see how it works, but I just want to make sure it's fairly tidy/obvious.

**Comment by narrenfrei** [comment]
@LisaFC I'm now going to bed with my kids. But I'll take a look a little bit later.

**Comment by narrenfrei** [comment]
@LisaFC 
I've tried to explain the settings of the taxonomy support here: https://www.docsy.dev/docs/adding-content/taxonomy/#parameters

Per default, in the right sidebar "clouds" (= lists of all terms of a taxonomy) get generated for all defined taxonomies (Hugo default: tags and categories). The title of these tags would be per default also tags and categories, but because in the current `config.toml` of the master branch of the Docsy userguide there are still fragments of my old test content:

```
[languages.no.taxonomies]
tag = "tags"
category = "categories"
project = "projects"
"norsk tag" = "norsk tags"
[languages.no.params.taxonomy]
taxonomyCloud = ["tags", "categories"] # set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloudTitle = ["Norsk Tag Cloud", "Norsk Cloud of Catagories"] # if used, must have same lang as taxonomyCloud
taxonomyPageHeader = ["projects", "tags", "norsk tags"] # set taxonomyPageHeader = [] to hide taxonomies on the page headers
```

```
[params.taxonomy]
taxonomyCloud = ["fruits", "text tags", "tags", "categories"] # set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloudTitle = ["Fruits are healthy", "Simple Tags Layout", "Tag Cloud", "Cloud of Catagories"] # if used, must have same lang as taxonomyCloud
taxonomyPageHeader = ["fruits", "text tags", "projects", "tags", "categories"] # set taxonomyPageHeader = [] to hide taxonomies on the page headers

[taxonomies]
tag = "tags"
category = "categories"
project = "projects"
"text tag" = "text tags"
fruit = "fruits"
```

Shall I prepare a PR with a simple taxonomy example for the Docsy userguide?
Any wishes for such a PR?

And once more: I'm really sorry, that I've made this problems by leaving my dev content in the PR. I think, it would be better, when I delete my dev content from the PR instead of leaving you a message, which files shouldn't be merged into master, in future.

**Comment by huehnerlady** [comment]
> I've tried to explain the settings of the taxonomy support here: https://www.docsy.dev/docs/adding-content/taxonomy/#parameters

@narrenfrei I have used this explanation to enable taxomonies in my blog and it worked, I found these instructions very good 🙂

**Comment by deining** [comment]
@narrenfrei: Great work, very useful, thanks a lot. Wile reading your instructions, I found a few typos which I corrected in #594. As @huehnerlady, I could follow the instructions easily, this may partially owed to the fact that I German is my mother tongue 🙂. I think there is room for improvement here and there. Maybe @LisaFC can step in here? Again, thanks your your hard work, I really appreciate that!

**Comment by huehnerlady** [comment]
@deining good point, my mother tongue is also German 😉

**Comment by narrenfrei** [comment]
Thanks for you comments.

After the message from  @huehnerlady I also thougt about whether I should also point out our common mother tongue ;-)

**Comment by LisaFC** [comment]
> Shall I prepare a PR with a simple taxonomy example for the Docsy userguide?
> Any wishes for such a PR?

That would be excellent thanks! What do you think would be a good demonstration of the feature?

I'll take a look at the new docs - they look excellent on a quick read, possibly just a few tweaks (and I may have some questions).

**Comment by narrenfrei** [comment]
As tags and categories are the default taxonomies from Hugo, I would keep this taxonomies at least for https://www.docsy.dev/docs/adding-content/taxonomy/

But what shall do with the tag and category cloud in the right sidebar? By default they are visible on all docs and blog pages. At the moment I only can switch them on/off globally.

**Comment by huehnerlady** [comment]
What are the use-cases for those? For me personally I just need them in blogs, so for me the natural thing is to enable it in blog and disable it anywhere else. 
but maybe that is an edge-case as theoretically every page in hugo can have tags/categories?

**Comment by narrenfrei** [comment]
As Docsy is specialist on documentation sites, most use cases will be in docs, I think.

Taxonomies can be used for a lot of (cool) things in docs - eg:

- assign development state
- topic specific responsible person
- collections for projects
- assign icons to content ;-) https://deploy-preview-554--docsydocs.netlify.app/fruits/

Every time when you want to give your content a additional dimension of structure you can use taxonomies and get so automatically pages for each taxonomy and taxonomy term. You can also serve additional content to this taxonomy term pages.

**Comment by huehnerlady** [comment]
I think for me that means adapting the docs page for now, which is fine by me, thank you for the explanation :)

**Comment by Symbolics** [comment]
If you don't mind, please let us know how you do this. I have the same requirement; tag clouds in blog, but not in docs.

**Comment by narrenfrei** [comment]
> If you don't mind, please let us know how you do this. I have the same requirement; tag clouds in blog, but not in docs.

At the moment you would have to make for you project modified templates for the docs section and comment the taxonomy clouds on the right column out. The listing of assigned taxonomy terms per page shouldn't disturb, because they only get shown when the current page have assigned taxonomy terms. 

For the next version of taxonomy support I plan a parameter in the config.toml to list the site sections, where to show the taxonomy infos or a page specific parameter to hide specific taxonomies. These parameter could get defined cascading, so all child pages also would use the same setting.

**Pull request merged**
