### PR TITLE
Upgrade to Bootstrap 4.6.2 (module install)

### PR DESCRIPTION
**Pull request by deining**
This PR syncs the versions of dependencies between Hugo modules and npm packages, as requested in #1182.
More concrete, it
* upgrades module/package FontAwesome to version 6..2.0 (npm + module install),
* upgrades package hugo-extended to hugo version 0..104.3 (npm install).
* updates go to latest version 1.19.2

### CODE REVIEW

**Review by dholbach — APPROVED** [review]

**Comment by chalin** [comment]
@deining - could you resolve the conflicts? I could do it, but it's probably safer for you to do so. Thanks. I'll merge soon afterwards so that this PR doesn't get conflicts again!

**Comment by deining** [comment]
> @deining - could you resolve the conflicts?

Done. Glad to see this merged!

**Review by chalin — APPROVED** [review]
Great, thanks!

**Comment by chalin** [comment]
For the record, after pulling this change in, and rerunning `npm install`, there are the differences is the generated site files:

```console
$ (cd userguide/public && git diff -bw --ignore-blank-lines -I "Hugo 0\.") | grep ^diff | grep -Ev '(.xml|_print)'
diff --git a/scss/main.css b/scss/main.css
diff --git a/scss/main.css.map b/scss/main.css.map
diff --git a/webfonts/fa-brands-400.ttf b/webfonts/fa-brands-400.ttf
diff --git a/webfonts/fa-brands-400.woff2 b/webfonts/fa-brands-400.woff2
diff --git a/webfonts/fa-regular-400.ttf b/webfonts/fa-regular-400.ttf
diff --git a/webfonts/fa-regular-400.woff2 b/webfonts/fa-regular-400.woff2
diff --git a/webfonts/fa-solid-900.ttf b/webfonts/fa-solid-900.ttf
diff --git a/webfonts/fa-solid-900.woff2 b/webfonts/fa-solid-900.woff2
diff --git a/webfonts/fa-v4compatibility.ttf b/webfonts/fa-v4compatibility.ttf
diff --git a/webfonts/fa-v4compatibility.woff2 b/webfonts/fa-v4compatibility.woff2
```

**Pull request merged**
