### PR TITLE
Adding shortcodes for tabbed panes

### PR DESCRIPTION
**Pull request by deining**
This PR adds two shortcodes `tabpane` and `tab` in order to allow authoring of tabbed panes. For a preview have a look at the implementation details and the documentation given here:

https://deploy-preview-507--docsydocs.netlify.app/docs/adding-content/shortcodes/#tabbed-panes

This PR was inspired and borrows both from the project [Hugo Dynamic Tabs](https://github.com/rvanhorn/hugo-dynamic-tabs) which is MIT-licensed and from this great [blog post](https://www.nirenjan.com/2019/bootstrap-navigation-tabs-in-hugo/). Shortcode names were modified in order to make them more comprehensible.

I hope you like the feature.

### CODE REVIEW

**Comment by deining** [comment]
This PR is now ready for review.

**Comment by osg** [comment]
The CSS looks broken to me. Please see the included image from Chrome on Ubuntu.
Screenshot from 2021-04-10 19-35-49

**Review by osg — CHANGES_REQUESTED** [review]
Please dig into the CSS for this change.

**Comment by deining** [comment]
> Please dig into the CSS for this change.

Thanks for pointing that out.
This is corrected now.

**Comment by LisaFC** [comment]
Oh I love this! Just a tweak or two to the docs.

**Pull request merged**
