### PR TITLE
Update de.toml

### PR DESCRIPTION
**Pull request by gethash**
Adds missing entry for post_view_this

### CODE REVIEW

**Comment by chalin** [comment]
Hi @gethash, thanks for this. You'll need to sign the CLA.

**Review by chalin — APPROVED** [review]
LGTM, once the CLA is signed.

**Comment by gethash** [comment]
Thanks - I did - Nov 30, 2021 06:54 PST

**Review by chalin — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
