### PR TITLE
Create new Hindi Localization hi.toml

### LINKED ISSUE #1617: add new Localize hi.toml file
add Hindi translation file in i18n

### PR DESCRIPTION
**Pull request by panchal20bhavin**
add on new Hindi localization file in i18n

This PR closes #1617.

### CODE REVIEW

**Review by deining — APPROVED** [review]
LGTM
Can you please sign the contributor's license?

**Comment by Bhavinpanchal20** [comment]
@deining  Yes i signed contributor's license.

**Review by LisaFC — APPROVED** [review]

**Comment by panchal20bhavin** [comment]
@deining Yes, I signed contributor's licence.

**Comment by emckean** [comment]
Hi, @panchal20bhavin could you please confirm that you've signed the CLA with the same email address as you used for teh commit? It's still not showing as signed.

**Comment by panchal20bhavin** [comment]
can you please tell me steps how I signed CLA?

**Comment by emckean** [comment]
Have you checked here? https://cla.developers.google.com/

**Pull request merged**
