### PR TITLE
Avoiding 'Illegal shortcode state' (Hugo v0.102.2)

### PR DESCRIPTION
**Pull request by deining**
This PR avoids an Ìllegal shortcode state`, thrown by Hugo version 0.102.x

### CODE REVIEW

**Comment by deining** [comment]
Rendering of user guide failed due to a regression introduced in hugo v0.102.0, fixed with recently released version hugo v0.102.3.    
I would like to keep this PR open though, since the syntax cahnge of the shortcode make sit easier to read. I still think it is a good thing to merge this PR.

**Comment by LisaFC** [comment]
Agree it's easier to read - I think we have some stuff in shortcodes (not sure about this one) that were added for compatibility with multiples of versions of Hugo ago.

**Comment by LisaFC** [comment]
This version renders properly with the previous version of Hugo, right?

**Comment by deining** [comment]
> This version renders properly with the previous version of Hugo, right?

Yes, it I tested it with hugo v0.101 and v0.102.x, and the result was always fine.

**Pull request merged**
