### PR TITLE
NPM dependencies: Update font-awesome package to include new twitter logo

### PR DESCRIPTION
**Pull request by venkyvajrala**
Fixes: #1753

### CODE REVIEW

**Comment by deining** [comment]
Thanks for your PR!
This PR takes care of the npm dependency. We have font-awesome as module dependency too, which also needs to be updated.
@venkyvajrala: can you add this missing part to the PR as well, please?

**Review by deining — CHANGES_REQUESTED** [review]
Thanks for your PR!
This PR takes care of the npm dependency. We have font-awesome as module dependency too, which also needs to be updated.
@venkyvajrala: can you add this missing part to the PR as well, please?

**Comment by venkyvajrala** [comment]
@deining Updated module dependency for font-awesome library.

**Review by chalin — APPROVED** [review]
LGTM, thanks 👍🏻 

FYI: In the past we've had patch updates to FA that affecting spacing, which is why I preferred waiting for 0.8.0 to be released first.

**Pull request merged**
