### PR TITLE
Add new github URL page param

### PR DESCRIPTION
**Pull request by LisaFC**
Lets users specify an explicit URL for a particular page's edit link, per #597

### CODE REVIEW

**Comment by LisaFC** [comment]
@laszewsk, PR to add feature to main theme.

**Comment by LisaFC** [comment]
Hmm, not sure why this is failing presubmits. Let me poke at it.

**Comment by LisaFC** [comment]
OK, all fixed (apparently I can't count {{end}} tags)

**Review by RichieEscarez — APPROVED** [review]
/lgtm

**Pull request merged**
