### PR TITLE
add google analytics support

### PR DESCRIPTION
**Pull request by thinkerou**
I know https://github.com/google/docsy-example/blob/master/config.toml#L52, but it seem invalid, so I commit the pull request.

### CODE REVIEW

**Comment by RichieEscarez** [comment]
@sarahmaddox I think that you have enabled analytics for your site, is this something that you can help review and validate?

**Comment by sarahmaddox** [comment]
@RichieEscarez Yes, I added Google Analytics to the Kubeflow site. I was able to do that without adding any additional JavaScript. So, I didn't need to add the `google-analytics.html` partial as this PR does.

Here's my PR - all I needed was to replace the dummy line `id = "INSERT ID"` with a line containing my actual Google Analytics ID:
https://github.com/kubeflow/website/pull/509/files
(The above PR also enables the feedback widget, which Docsy supplies coupled with GA.)

@thinkerou Is the difference that you've added Google Tag Manager to your site, as well as Google Analytics?
https://stackoverflow.com/questions/23640645/what-is-the-difference-between-google-tag-manager-and-google-analytics#

**Comment by emckean** [comment]
Closed as original PR author not responding. Please feel free to reopen!

**Pull request closed without merging**
