### PR TITLE
Scripts: get bootstrap.js and popper.js at build time

### PR DESCRIPTION
**Pull request by chalin**
- Contributes to:
  - #1182
  - #605 by eliminating the CDN call to Bootstrap and making the CDN call to Popper at build time

### CODE REVIEW

**Comment by chalin** [comment]
As is mentioned in [Components] from the Bootstrap docs:

> Tooltips and popovers [are used] for displaying and positioning (also requires [Popper](https://popper.js.org/))

Tooltips are still working (they're used in the footer):

> image

[Components]: https://getbootstrap.com/docs/4.6/getting-started/introduction/#components

**Review by LisaFC — APPROVED** [review]
Looks good!

**Comment by chalin** [comment]
Thanks for the review. Merged so that I can more easily experiment with:

- #470

**Comment by deining** [comment]
This commit broke docsy module installations. We need to add a mount so that bootstrap.js becomes available with module installations (see PR #1216).

**Pull request merged**
