### PR TITLE
Add Persian language translations and override some styles in rtl direction

### PR DESCRIPTION
**Pull request by theSinner**
Hi

I added the Persian language and also override some styles in RTL direction and add [Vazir](https://github.com/rastikerdar/vazir-font) font when the language is Persian which is a good-looking open-source Persian font.

Here is the Docsy Example in the Persian language:

Screen Shot 2020-11-26 at 16 34 26
Screen Shot 2020-11-26 at 16 34 39
Screen Shot 2020-11-26 at 16 35 09

I also added Persian content in the docsy-example project.

### CODE REVIEW

**Comment by theSinner** [comment]
@googlebot I signed it!

**Comment by gwatts** [comment]
wow that looks really good - Missing a few of the newer strings that were added to `en.toml` in a recent commit; might be nice to include those for completeness?

**Comment by theSinner** [comment]
> wow that looks really good - Missing a few of the newer strings that were added to `en.toml` in a recent commit; might be nice to include those for completeness?

Of course. I added them in my new commit.

**Comment by LisaFC** [comment]
This is great, thanks so much!

**Pull request merged**
