### PR TITLE
Userguide: fix broken link, amend links, update content

### PR DESCRIPTION
**Pull request by deining**

### CODE REVIEW

**Comment by LisaFC** [comment]
Thanks for this! Can you check your branch's package.json against the one in our main branch, there seem to be some prereqs missing for the Netlify preview.

**Comment by deining** [comment]
> Can you check your branch's package.json against the one in our main branch

I reverted `autoprefixer` version from 9.5.0 to 5.01 and `postcss-cli`version from 7.2 to 5.0.1, and now the deloymnet to netlify succeeds.
Please note that these dependency upgrades on my branch weren't authored by me, they were introduced into the main branch with your commit b3b482314b864a234cb5339219a08ca63d150c60 `bump postcss-cli version` two days ago.
Maybe you can have a look at this and fix this, otherwise future pull requests will most likely fail again.

**Comment by LisaFC** [comment]
I'll take a look - it's odd that it was a breaking change, as the actual Docsy site publishes fine from Netlify with the same deps.

**Comment by LisaFC** [comment]
This is great, thanks! I'll have a look at bumping the deps again after I've merged your updates.

**Pull request merged**
