### PR TITLE
Use hugo.IsProduction instead of checking HUGO_ENV

### LINKED ISSUE #652: Changes introducing hugo.IsProduction were overwritten
_Originally posted by @chalin in https://github.com/google/docsy/issues/611#issuecomment-895335837_

---

@LisaFC et al.: somehow #540 reverted #413. The latter introduced the use of `hugo.IsProduction`, in replacement of the environment-variable checking code. IMHO, use of `hugo.IsProduction` is the better (if not proper) way to determine the build environment, in particular since the build environment can be specified using the [-e flag][] command line flag.

[-e flag]: https://gohugo.io/commands/hugo/#options

Possibly related: #611
Related: #651

/cc @nate-double-u

### PR DESCRIPTION
**Pull request by chalin**
- Reapplies #413, which was removed by mistake in #540. For details, see https://github.com/google/docsy/pull/540/files#r685339766
- Closes #652

### CODE REVIEW

**Comment by chalin** [comment]
@LisaFC - given that this essentially fixes a regression, can it be merged soon? /cc @nate-double-u

**Comment by LisaFC** [comment]
Yep, I'm just looking at it now - the main thing is that it needs to be documented and announced because it's a breaking change with regard to whether your site is indexed.

(which I didn't think the original change was because I hadn't fully explored the mysterious ways of how the relevant environment variable and the current Hugo environment are not the same thing, as I did in #611)

**Comment by chalin** [comment]
Thanks. AFAICT, `hugo.IsProduction` will be true if `HUGO_ENV=production` is set, so it might not be a breaking change.

**Comment by LisaFC** [comment]
I *think* that's true but I need to check, I remember finding some unintuitive behaviour when I explored it in #611 

We also need to document for the case where `HUGO_ENV=production` is *not* set and the user expects their site not to be indexed - if we make this change it *will* be indexed unless they explicitly specify that this is a non-production build.

**Comment by LisaFC** [comment]
> Thanks. AFAICT, `hugo.IsProduction` will be true if `HUGO_ENV=production` is set, so it might not be a breaking change.

Annoyingly, I just checked, and it isn't (or at least `HUGO_ENV`=production in your Netlify setup doesn't override setting an environment in your hugo command with `-e`) - though it shouldn't be a problem anyway for existing sites as users will get a production build by default.

**Comment by chalin** [comment]
Right, `production` is the default for the `build` command. It makes sense that `-e` takes precedence. 

Btw, let me know if there is anything I can do to help.

**Pull request merged**
