### PR TITLE
Update nl

### PR DESCRIPTION
**Pull request by erwin-faceit**
Added the missing translations for the Dutch language.

### CODE REVIEW

**Comment by deining** [comment]
Thanks for your contribution!

The Dutch language file contains a `Community` section with a few phrases that are not translated yet. Can you please provide translations for these texts as well? Thanks in advance!

https://github.com/google/docsy/blob/d9bf98b876d74772b850ef910c6f59b898f61ccf/i18n/nl.toml#L61-L77

**Comment by erwin-faceit** [comment]
> The Dutch language file contains a `Community` section with a few phrases that are not translated yet. Can you please provide translations for these texts as well? Thanks in advance!

I did my best. Not all sentences would be translated like that to Dutch, but I think it should be fine like this. I haven't seen or used the community pages yet, so I'm not entirely sure how these strings are used in the content. Is there some kind of sample page so I can verify these translations?

**Comment by deining** [comment]
> I did my best. Not all sentences would be translated like that to Dutch, but I think it should be fine like this.

Great, thanks! Looks good to me!

> I haven't seen or used the community pages yet, so I'm not entirely sure how these strings are used in the content. Is there some kind of sample page so I can verify these translations?

These strings are used in the community section of the user guide:

https://www.docsy.dev/community/

**Comment by erwin-faceit** [comment]
Excellent, looks good to me then!

**Comment by deining** [comment]
Thanks for your additional tranlation which looks good to me.

I realized however, that two texts are still missing in the Dutch translation file `nl.toml`:

https://github.com/google/docsy/blob/d9bf98b876d74772b850ef910c6f59b898f61ccf/i18n/en.toml#L19-L21

https://github.com/google/docsy/blob/d9bf98b876d74772b850ef910c6f59b898f61ccf/i18n/en.toml#L40-L41

Can you please add and translate these two texts, too? Thanks in advance.

**Comment by erwin-faceit** [comment]
These are already part of this PR:

https://github.com/erwin-faceit/docsy/blob/5f6eb8dffc6714a0bddb57868c43b3edbce90a9f/i18n/nl.toml#L21-L22

https://github.com/erwin-faceit/docsy/blob/5f6eb8dffc6714a0bddb57868c43b3edbce90a9f/i18n/nl.toml#L40-L41

**Comment by deining** [comment]
> These are already part of this PR:

Oops, sorry you are right.

Merged now, thanks for your contribution!

**Pull request merged**
