### PR TITLE
[UG] Give guidance on what to do on "failed to load modules" error

### LINKED ISSUE #2116: [CI] Docsy 0.8.0 NPM-package use may fail
This was uncovered by @sftim through his work on

- https://github.com/kubernetes/website/issues/41171

To reproduce the problem, run the following:

```sh
hugo new site --format yaml myproject
cd myproject
echo 'theme: docsy' >> hugo.yaml
echo 'themesDir: node_modules' >> hugo.yaml
npm init -y
npm install --save-dev google/docsy#semver:0.8.0 autoprefixer postcss-cli
hugo # Ensure that it is v0.120.4
```

Hugo reports: "Error: failed to load modules: module "github.com/FortAwesome/Font-Awesome" not found in "/Users/chalin/tmp/myproject/node_modules/github.com/FortAwesome/Font-Awesome"; either add it as a Hugo Module or store it in "/Users/chalin/tmp/myproject/node_modules".: module does not exist"

The problem is that Docsy's `postinstall` NPM script isn't being run automatically, but it should.

### PR DESCRIPTION
**Pull request by chalin**
- Fixes #2116
- Gives guidance on what to do if Hugo reports a "failed to load modules" error when using Docsy via NPM
- Ran Prettifier over the updated files
- Makes setting of `themesDir` in the sample config the "happy path"
- **Preview**: https://deploy-preview-2117--docsydocs.netlify.app/docs/get-started/other-options/#option-3-docsy-as-an-npm-package

### CODE REVIEW

**Review by LisaFC — APPROVED** [review]

**Comment by sftim** [comment]
A related concern; the postinstall I think runs `cp -R node_modules/bootstrap/scss/vendor/* assets/_vendor/bootstrap/scss/` and this is making assumptions about both the current working directory and the name of the install target.

Seems like NPM might not guarantee those are always the right values to make that command work.

**Comment by chalin** [comment]
For the `cp` command, we've switched to use of the NPM `cpy-cli` command. As for the working directory, I'll leave that as is for now. We can address any specific issues if/when they arise.

**Comment by chalin** [comment]
@sftim - btw, unless you run `ci:prepare` you won't hit the copy commands. The `ci:prepare` is only for those maintaining and releasing Docsy.

**Pull request merged**
