### PR TITLE
Add markmap supported

### PR DESCRIPTION
**Pull request by llhhbc**
Add markmap supported for write mindmap with markdown.

You can know markmap by https://markmap.js.org/repl  and https://github.com/gera2ld/markmap/tree/master/packages/markmap-autoloader

### CODE REVIEW

**Comment by llhhbc** [comment]
https://github.com/google/docsy/issues/610

**Comment by LisaFC** [comment]
This is great! Can you add some brief documentation in https://www.docsy.dev/docs/adding-content/lookandfeel/ with all the other map/chart/diagram features? Doesn't need to be perfect, I can do an editorial review.

**Comment by llhhbc** [comment]
> This is great! Can you add some brief documentation in https://www.docsy.dev/docs/adding-content/lookandfeel/ with all the other map/chart/diagram features? Doesn't need to be perfect, I can do an editorial review.

Pull a merge request to this docs's project? I will try.

**Comment by LisaFC** [comment]
> > This is great! Can you add some brief documentation in https://www.docsy.dev/docs/adding-content/lookandfeel/ with all the other map/chart/diagram features? Doesn't need to be perfect, I can do an editorial review.
> 
> Pull a merge request to this docs's project? I will try.

Yes thanks! I'll happily do any editing required. :)

**Comment by llhhbc** [comment]
> > > This is great! Can you add some brief documentation in https://www.docsy.dev/docs/adding-content/lookandfeel/ with all the other map/chart/diagram features? Doesn't need to be perfect, I can do an editorial review.
> > 
> > 
> > Pull a merge request to this docs's project? I will try.
> 
> Yes thanks! I'll happily do any editing required. :)


Sorry for the delay, I have already added the relevant document description

**Comment by LisaFC** [comment]
Thanks! Sorry for the late review, I was on vacation. Will take a look now!

**Comment by LisaFC** [comment]
This looks great! Thanks for adding the feature!

**Pull request merged**
