### PR TITLE
Foldable sidebar (Issue #342)

### PR DESCRIPTION
**Pull request by narrenfrei**
As already discussed in #342 this is my suggestion for a foldable sidebar menu. It should also work with a cached sidebar menu. I've also added some general CSS tweaks for the sidebar menu.

Here you can find a preview (that also have set icons in the sidebar menu partly): https://deploy-preview-518--docsydocs.netlify.app/docs/

I've also added a short how to: https://deploy-preview-518--docsydocs.netlify.app/docs/adding-content/navigation/#section-menu

This PR is based on the PR #511 (manual extern links) and should merged after it.

### CODE REVIEW

**Comment by narrenfrei** [comment]
@LisaFC After bringing my dev branch up to date with the current master from Docsy, the cla/google bot says: "CLAs are signed, but unable to verify author consent". I don't really know why? Do you (or anybody else) know why, and more important how to solve it?

**Comment by narrenfrei** [comment]
FYI: the PR also includes a few minor changes, as the sidebar menu was a bit wasteful with space (every UL tag got a padding right - also the nested ones!).

**Comment by narrenfrei** [comment]
From my side this PR would be ready (except some code cleaning and polishing).

Would be grateful for feedback or if someone would find time to test:
https://deploy-preview-518--docsydocs.netlify.app/docs/

**Comment by LisaFC** [comment]
@emckean, do you know what's going on with the Google CLA bot?

I'll take some time later today/tomorrow to have a look at the actual functionality in the PR! Thanks for this!

**Comment by narrenfrei** [comment]
As the PR is ready from my side, I've removed the WIP in the label.

When merging you should exclude:

config.toml
userguide/content/blog
userguide/content/en/docs/dev-test-content

**Comment by narrenfrei** [comment]
Would be great, if we could get this merged soon.
The Problem with the google-cla bot should be the same as in #554

**Comment by narrenfrei** [comment]
@LisaFC Shall I remove my test content from the PR, that you can simply merge it?

**Comment by RichieEscarez** [comment]
I think I resolved the "merge conflicts" that were blocking this PR (do [take a look to validate](https://github.com/google/docsy/pull/518/commits/0fbaa0655c737ee3087c69843651ac40658f4b09)) but I'll let @LisaFC handle the final review/merging of the content.

**Comment by LisaFC** [comment]
Looks good!

**Pull request merged**
