### PR TITLE
Resubmitting PR #509 (on behalf of original author)

### PR DESCRIPTION
**Pull request by deining**
PR #509 could not be merged due to CLA issues. I'm stepping in and resubmit this PR as is, rebased on HEAD. For my understanding, the PR is ready for merging. Please correct me if I'm wrong here.

### CODE REVIEW

**Comment by deining** [comment]
After pulling in the files from hühnrladys repo, there were still CLA issues. Resubmitted the files with me as author only. Eventually, CLA isse should be resolved now.

**Comment by huehnerlady** [comment]
@deining super cool, thank you so much for stepping in :)

**Comment by LisaFC** [comment]
Thanks for doing this!

**Comment by dseynaev** [comment]
I think this PR removed a little too much: hugo allows to set LastMod as a page variable. Even without git info, it could still be useful to show the last modified date if it is set manually.

**Pull request merged**
