### PR TITLE
Updating the config.toml file format

### PR DESCRIPTION
**Pull request by priyansh19**
This is a non mandatory update but needs to be done as the comments are done just above or below the line of code to help understand it better.

### CODE REVIEW

**Comment by priyansh19** [comment]
Can you send me the invite link for joining this organisation

**Comment by LisaFC** [comment]
This is very helpful, thanks!

**Comment by priyansh19** [comment]
> This is very helpful, thanks!

LisaFC please send me the invite link for joining google organization. I want to contribute into it more .. this was just a test contribution by me

**Comment by priyansh19** [comment]
> This is very helpful, thanks!

LisaFC please send me the invite link for joining google organization. I want to contribute into it more .. this was just a test contribution by me

**Comment by priyansh19** [comment]
Can you send me the invite link for joining the Google Organisation on
github

**Comment by priyansh19** [comment]
Github Username - Priyansh19

**Comment by LisaFC** [comment]
I can't invite people to the Google org, I'm afraid, I just have a project in it.

**Comment by priyansh19** [comment]
so how will we get invite link from organisations ?

**Comment by LisaFC** [comment]
Only organization owners can invite members, and I'm not an owner in this org.

**Comment by priyansh19** [comment]
do you have an email id of any owner of this organisation ?

**Comment by LisaFC** [comment]
I don't, sorry!

**Comment by priyansh19** [comment]
Ok , No thanks

**Pull request merged**
