### PR TITLE
Make docsy point to latest version of dependencies

### PR DESCRIPTION
**Pull request by deining**
This This PR is related to #1409. It ensures that we use and test docsy (module setup) with latest version of dependencies.

### CODE REVIEW

**Review by chalin — COMMENTED** [review]
Hi @deining: is it still relevant to merge this? If so, does it need updating first?

**Comment by deining** [comment]
> Hi @deining: is it still relevant to merge this?

Yes.

> If so, does it need updating first?

Yes, since Font-Awesome is at 6.4.0 meanwhile.

The correct order of tasks would be:
- you review and merge #1529
- I update this PR (#1418)
- you review and merge this PR (#1418)

**Comment by chalin** [comment]
Thanks for the guidance @deining, it's much appreciated as I context switch between projects. 
#1529 has been merged.

**Comment by deining** [comment]
> @deining - looking forward to this update so that we can proceed with the release of 0.7.0. Thanks! /cc @geriom

I inadvertently closed this issues and don't have sufficient rights to reopen it. Authored new PR #1533 instead.

**Comment by chalin** [comment]
Strange that you wouldn't have the rights to reopen your own PR. Thanks for #1533.

**Pull request closed without merging**
