### PR TITLE
icons for header menu

### PR DESCRIPTION
**Pull request by narrenfrei**
add icons to header menu items like explained in Hugo docs (https://gohugo.io/content-management/menus/#add-non-content-entries-to-a-menu)

### CODE REVIEW

**Comment by narrenfrei** [comment]
I've published a preview of my changes:
http://docsy-dev-4.narrenfrei.at

In my PR I've also added icons to the header menu icons of the userguide. I don't know, if this is wanted or not. You can delete them of course.

This PR is part of my suggestion for #457

**Comment by LisaFC** [comment]
Oh this is really nice! Made some minor updates to the docs section. Are there any dependencies here on other PRs or can we merge this now?

**Comment by narrenfrei** [comment]
> Oh this is really nice! Made some minor updates to the docs section. Are there any dependencies here on other PRs or can we merge this now?

No, there are no dependencies. I pack the PRs in such a way that there should be no dependencies. Wherever dependencies arise, I wait with further PRs until required PRs have already been merged.

For your info, these PRs are planned from my side:
1. Restructuring of the sidebar menu: #475 (MERGED) and #483
2. Icons in header menu: #480 (this one)
3. Icons in sidebar menu: #485 (WIP, feedback needed)

When #483 and #485 are merged:

4. External links: #449
5. Foldable Sidebar Menu: #342 
6. JS: scrolling to active sidebar menu item: #348
7. some CSS tweaks
8. Some tweaks for Tagging as update to #324

**Comment by LisaFC** [comment]
Perfect! I'm happy to merge this one now.

**Pull request merged**
