### PR TITLE
Turning docsy theme into a  hugo module

### PR DESCRIPTION
**Pull request by deining**
@LisaFC: Can you please merge this PR into the feature branch? The merge will give me a commit hash that I can refer to in my future work in this feature branch. Thanks.

### CODE REVIEW

**Comment by deining** [comment]
In order to make fast progress here, it were great if you could allow me to bypass pull request requirements for this feature branch. The GitHub docu about [branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule) has more details on this. Thanks for looking into this.

**Comment by chalin** [comment]
> Can you please merge this PR into the feature branch? The merge will give me a commit hash that I can refer to in my future work in this feature branch

Done!

**Comment by chalin** [comment]
> In order to make fast progress here, it were great if you could allow me to bypass pull request requirements for this feature branch

@emckean or @LisaFC will have to do this, I don't have the permissions.

**Comment by chalin** [comment]
Paraphrasing from https://github.com/google/docsy/pull/796#discussion_r771522516:

> Why is `assets/bootstrap/scss/vendor/_rfs.scss` being brought in separately as opposed to getting it via the BS module?

**Comment by deining** [comment]
> Paraphrasing from [#796 (comment)](https://github.com/google/docsy/pull/796#discussion_r771522516):
> 
> > Why is `assets/bootstrap/scss/vendor/_rfs.scss` being brought in separately as opposed to getting it via the BS module?

See this [comment](https://github.com/gohugoio/hugo/issues/6945#issuecomment-590270825) for an explanation.

**Pull request merged**
