### PR TITLE
add option to translate feedback question and options

### LINKED ISSUE #175: i18n of page feedback
Currently the `feedback.html` partial is not internationalized as the values are hardcoded into English. 
https://github.com/google/docsy/blob/1b46d71fe3c1894cc17e0b2be066dc5345cbb616/layouts/partials/feedback.html#L17-L19

I've changed the files in my local repo to resolve this issue. If you the maintainers are happy to accept a PR for this I would like to submit it. If you wanna have a look at the current state see here: https://github.com/tobiaskohlbau/docsy/commit/ed57f05f89fe38837a69418e2cb5b33c54d1ee26

### PR DESCRIPTION
**Pull request by tobiaskohlbau**
Fixes #175 

Would like to gather more languages. Any chance there are people around who speak the missing languages?

### CODE REVIEW

**Comment by LisaFC** [comment]
Great! I'll send a mail to the docsy-users group to see if any other community members can add the strings to our other language bundles.

**Comment by tobiaskohlbau** [comment]
I'm unclear where the right place is to document the option to translate the ui settings.

```
[languages.de]
[languages.de.params]
[languages.de.params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Schön zu hören! Bitte <a href="https://github.com/myopenfactory/docs/issues/new">teilen Sie uns mit, wie wir uns verbessern können.</a>.'
no = 'Tut uns leid das zu hören. Bitte <a href="https://github.com/myopenfactory/docs/issues/new">teilen Sie uns mit, wie wir uns verbessern können</a>.'
[languages.en]
[languages.en.params]
[languages.en.params.ui.feedback]
enable = true
## The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/myopenfactory/docs/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/myopenfactory/docs/issues/new">tell us how we can improve</a>.'
```

In addition I'm not quiet comfortable with toml. I've expierienced that I need to put the enabled in both fields as the global one get's overwritten by the language specific ones (empty key).

**Comment by LisaFC** [comment]
For the documentation, I'd mention it in this page on feedback, under Setup:

https://github.com/google/docsy/blob/master/userguide/content/en/docs/Adding%20content/feedback.md

Something like "The feedback widget text itself depends on your chosen language. If your preferred language isn't supported yet, please add the text to the relevant [internationalization bundle](...)"

...and then link to the multi-language support page where it discusses the internationalization bundles: https://www.docsy.dev/docs/language/#internationalization-bundles

I'll have a play around with the config for setting this up - we presumably don't want users to have to enable/disable feedback on a per-language basis.

**Comment by LisaFC** [comment]
Haven't forgotten about this, btw, was travelling for work - will play around with the config this week.

**Comment by hajekj** [comment]
Hello @LisaFC, do you think we could get this merged? Would be really awesome! Thanks!

**Comment by LisaFC** [comment]
Thanks for the reminder! I'll have a look at the files, I seem to remember they weren't quite right/ready to merge.

**Comment by tobiaskohlbau** [comment]
I'm eager to address any open changes to align with the project.

I will try to have another look from my side in the upcoming days.

**Pull request closed without merging**
