### PR TITLE
Resolves the breaks in github's preview tab

### PR DESCRIPTION
**Pull request by mahi072**
issue #668
The proposed changes is the enhancement of code to remove the parent filename in the GH repo path.
Preview tab is also now works as expected.

### CODE REVIEW

**Comment by mahi072** [comment]
Hi @chalin, @spkane,
Please review my PR, and provide any feedback on this if required.

**Comment by spkane** [comment]
@mahi072 I am not a contributor to this repo. I'd recommend trying to reach someone who has contributed to the main branch recently.

**Comment by mahi072** [comment]
Hi @deining, @chalin 
Can you please review this PR, and provide your feedback.

**Comment by mahi072** [comment]
Hi @chalin , @deining, Can you please review this PR?
It is resolving the issue #668

**Comment by mahi072** [comment]
Hi @chalin, @deining, Please review the PR.
It is academically very important for me.

**Pull request closed without merging**
